defaults:
  repo:
    visibility: public
    default_branch: main
    allow_update_branch: true
    license:
      key: gpl-3.0
  actions:
    actions_permissions:
      enabled: true
      allowed_actions: all
    workflow_permissions:
      default_workflow_permissions: write
      can_approve_pull_request_reviews: false
  protection:
    branches:
      <repo.default_branch>:
        required_status_checks:
          strict: true
          contexts: []
        required_pull_request_reviews:
          dismiss_stale_reviews: false
          require_code_owner_reviews: false
          required_approving_review_count: 0

    tags:
      - v*
